Repository CodeForAfrica/sensors.AFRICA-SeaSensors, pull requests merged in 2019-06, with the labels that each got.

#30 Navigation
  package.json
  src/assets/icons/menu.svg
  src/components/Navigation.js
  yarn.lock
Labels: enhancement

#36 Hero component for pages
  src/components/AboutUsHeader.js
  src/components/Navigation.js
  src/components/NewsHeader.js
  src/components/ResourcesHeader.js
  src/components/SharedHeader.js
Labels: bug, enhancement

#42 Make resource page mobile responsive
  src/components/ResourceCards/ResourceCards.js
  src/components/ResourceCards/index.js
  src/components/ResourcesHeader.js
Labels: bug, enhancement

#43 Make Video & Audio Stories mobile responsive
  src/components/NewsPrintStories.js
  src/components/NewsTitleText.js
  src/components/NewsTopStories.js
  src/components/SectionTitle.js
  src/components/VideoAudioSrories.js
  src/components/VideoAudioStories.js
  src/pages/news.js
Labels: bug, enhancement

#46 Fix Equipment HotSpot Map Popover
  src/components/Equipment/index.js
Labels: bug

#48 [Hotfix] News components medium screen layout improvement
  src/components/MonthlyStories/NewsCard.js
  src/components/MonthlyStories/Stories.js
  src/components/MonthlyStories/StoryOfTheMonth.js
  src/components/MonthlyStories/index.js
  src/components/Section.js
  src/components/VideoAudioStories.js
  src/pages/news.js
Labels: bug, enhancement

#49 Update blast graph info
  src/components/Blasts/BlastVisual.js
Labels: bug

#41 Make About page mobile responsive
  src/assets/fisheries.png
  src/assets/fisheries@2x.png
  src/assets/fisheries@3x.png
  src/assets/nukta.png
  src/assets/nukta@2x.png
  src/assets/nukta@3x.png
  src/components/AboutImportantHeader.js
  src/components/AboutUsHeader.js
  src/components/BlastDeployment.js
  src/components/GetInvolved.js
  src/components/Navigation.js
  src/components/NewsHeader.js
  src/components/OurPartners.js
  src/components/ResourcesHeader.js
  src/components/Team/CardContainer.js
  src/components/Team/index.js
  src/components/ViewGallery/GalleryContainer.js
  src/components/ViewGallery/index.js
Labels: bug, enhancement

#50 Add equipment content
  src/components/Equipment/ButtonContent/FirstScuba.js
  src/components/Equipment/ButtonContent/SecondScuba.js
  src/components/Equipment/ButtonContent/ThirdScuba.js
  src/components/Equipment/index.js
Labels: bug, enhancement

#51 [Hotfix] Dummify wavesurfer module during SSR
  gatsby-node.js
  package.json
  yarn.lock
Labels: bug, enhancement

#53 Review site v0.0.3
  src/components/Equipment/ButtonContent/FirstScuba.js
  src/components/IndexHeader/HeaderText.js
  src/components/NewsHeader.js
Labels: bug, enhancement

#54 Read blasts information from a gSheet
  src/components/Blasts/BlastVisual.js
Labels: enhancement

#56 Update site content and links
  src/components/AboutImportantHeader.js
  src/components/AboutUsHeader.js
  src/components/Blasts/BlastVisual.js
  src/components/Blasts/index.js
  src/components/Footer.js
  src/components/GetInvolved.js
  src/components/IndexHeader/Wave.js
  src/components/MonthlyStories/index.js
  src/components/NewsHeader.js
  src/components/OurPartners.js
  src/components/Partners.js
  src/components/ResourcesHeader.js
  src/components/Stories/index.js
  src/components/Team/index.js
  src/components/VideoAudioStories.js
Labels: bug, enhancement

#57 [Site][Fix]Fix blast data in graph
  src/components/Blasts/BlastVisual.js
Labels: bug

#58 [Feedback] How it works section
  src/components/Equipment/index.js
  src/components/More.js
  src/components/TextSection/TextSection.js
Labels: bug, enhancement

#61 [Feedback] Remove description from sea sensor stories section
  src/components/Stories/MediaCard.js
Labels: bug, enhancement

#59 [Feedback] Fix breakpoint for medium devices
  src/components/OurPartners.js
  src/components/Team/CardContainer.js
Labels: bug, enhancement

#60 [Site][Feedback]Fix responsiveness of assets on homepage
  src/components/Equipment/ButtonContent/FirstScuba.js
  src/components/Equipment/ButtonContent/SecondScuba.js
  src/components/Equipment/ButtonContent/ThirdScuba.js
  src/components/Equipment/index.js
  src/components/Video.js
Labels: bug, enhancement
